### ISSUE TITLE
Recommended way to setup SQLAlchemy

### ISSUE THREAD

**Issue by fraunos** [gtalarico/flask-vuejs-template#13]
Hi,
I'm new to Python and Flask - I'm trying to setup a db connection in a project based on this template, which is quite problematic for me. I'm following some tutorials, but some are outdated and most show only very simple setups. (http://exploreflask.com/en/latest/storing.html http://flask-sqlalchemy.pocoo.org/2.3/)

While trying to use `current_app` imported from `flask` in a `db.py` file based in `app/api` I get
```
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
```

Currently the error I'm facing is -
```
/home/michalw/dev/python/venv/bin/python: Error while finding module specification for 'app.__main__' (ImportError: cannot import name 'db' from 'app' (/home/michalw/dev/python/flask-vuejs-template/app/__init__.py))
```
I imported and initialized `flask_sqlalchemy` in `app/__init__.py`.

So I've got following questions:
- which file should SQLAlchemy be imported in and db object initialized
- how to use db object outside this file to declare models classes
- should I use Blueprint for that? How?

**Comment by gtalarico** [comment]
Hi @fraunos - 
Tour question is complex and probably better suited for a stack overflow post rather than an issue on this repository, so I am closing this since it's not related to the template.

But since I remember the pain of running into this issue, I add add some thoughts and links, hopefully they will help.

> RuntimeError: Working outside of application context.
You should *absolutely* watch this video from Miguel Grindberg:
https://blog.miguelgrinberg.com/post/flask-webcast-2-request-and-application-contexts

After watching the video this should be very easy to understand:
http://flask-sqlalchemy.pocoo.org/2.3/contexts/
http://flask.pocoo.org/docs/1.0/appcontext/#creating-an-application-context


> cannot import name 'db' from 'app'
It's hard to say anything about this without seeing the whole repo, but from the sound of it it's probably a circular import issue, like [this one](https://stackoverflow.com/a/41839910)

And this:
[Flask Circular Imports] (https://www.youtube.com/watch?v=NH-8oLHUyDc)

> which file should SQLAlchemy be imported in and db object initialized
> how to use db object outside this file to declare models classes
[Example](https://github.com/ltalirz/flask-sqlalchemy-circular-imports)
[Example 2](https://github.com/mitsuhiko/flask-sqlalchemy/pull/250#issuecomment-377080229)

> should I use Blueprint for that? How?
Up to you. 
My thoughts on blueprints is to avoid them until they are needed.... 
You will know when you need them

**Comment by fraunos** [comment]
Thanks a lot, it helped me clarify these problems
